exclude_self: true

excluded_relationship_types:
  - spouse
  - dating

avoid_previous_years: 0

prevent_reciprocal_pairs: true

giver_draw_mode: "without_replacement"
recipient_draw_mode: "without_replacement"
