people:
  - id: alice
    name: Alice
    desired_items:
      - Coffee
    shirt_size: M

  - id: bob
    name: Bob
    desired_items:
      - Books
    shirt_size: L


relationships:
  - type: spouse
    direction: bidirectional
    groups:
      - people: [alice]
      - people: [bob]